spring:
  application:
    name: acc-svc
  redis:
    host: 192.168.50.33
    port: 9981
    password: 'hhhhhhhhhhsdvnsldvmsdlvmsdlkvmsdv'
    database: 6
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
      shutdown-timeout: 200ms
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    mongodb:
      host: 18.139.222.137
      port: 27017
      database: 'resume'
      username: 'resume'
      password: 'abc123resume'

server:
  port: ${ACCOUNT_SVC_PORT:30302}
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:30300/eureka/}

logging:
  config: config/log4j2.xml

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

zuul:
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

application:
  version: ${VERSION:1.0}

company:
  favicon:
    domain: http://file-rs.edsolabs.com/favicon/
    path: /usr/share/nginx/file-rs/favicon/
    # path: D:\
  logo:
    domain: http://file-rs.edsolabs.com/logo/
    path: /usr/share/nginx/file-rs/logo/
    # path: D:\
